version: "3.8"

networks:
  rafat97__network:
    name: rafat97__network

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.DEV
    image: "auth-service:v1"
    restart: always
    environment:
      - "APP_PORT=9050"
    ports:
      - "9050:9050"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - rafat97__network
