name: Version Change Action

on:
  push:
    # branches: [master, main, develop, staging]
    branches: [master]

  # pull_request:
  #   branches: [master, main, develop, staging]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: |
          echo "Hello ${{ github.event.inputs.name }}"

  version_change:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update version in package.json
        run: |
          git config --local user.email "rafathaque.bot@gmail.com"
          git config --local user.name "rafat97bot"
          npm --no-git-tag-version version patch 
          git status
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: version update by bot
          commit_user_name: rafat97bot
          commit_user_email: rafathaque.bot@gmail.com
          commit_author: Rafat97[BOT] <rafathaque.bot@gmail.com>
